# Generated by Django 3.2.6 on 2021-09-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, error_messages={'unique': 'A title already exists.'}, help_text='Required. 150 characters or fewer. digits only.', max_length=150, null=True, unique=True, verbose_name='title')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_image/', verbose_name='course_image')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
