# Generated by Django 3.2.6 on 2021-09-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(blank=True, help_text='Required. 250 characters or fewer. digits only.', max_length=250, null=True, verbose_name='chapter_name')),
                ('module_id', models.IntegerField(blank=True, null=True, verbose_name='module_id')),
                ('course_id', models.IntegerField(blank=True, null=True, verbose_name='course_id')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('discussions', models.TextField(blank=True, null=True, verbose_name='discussions')),
                ('bookmarks', models.TextField(blank=True, null=True, verbose_name='bookmarks')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('chapter_file', models.FileField(blank=True, null=True, upload_to='chapter_file/', verbose_name='chapter_file')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(blank=True, error_messages={'unique': 'A title already exists.'}, help_text='Required. 250 characters or fewer. digits only.', max_length=250, null=True, unique=True, verbose_name='module_title')),
                ('course_id', models.IntegerField(blank=True, null=True, verbose_name='course_id')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='author')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='rating')),
                ('total_hours', models.CharField(blank=True, max_length=6, null=True, verbose_name='total_hours')),
                ('total_days', models.IntegerField(blank=True, null=True, verbose_name='total_days')),
                ('selling_price', models.CharField(blank=True, max_length=6, null=True, verbose_name='selling_price')),
                ('original_price', models.CharField(blank=True, max_length=6, null=True, verbose_name='original_price')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('module_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='module_level')),
                ('bestseller', models.IntegerField(blank=True, null=True, verbose_name='bestseller')),
                ('module_file', models.FileField(blank=True, null=True, upload_to='module_file/', verbose_name='module_file')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
