# Generated by Django 3.2.6 on 2021-09-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_chapter_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='date',
            field=models.DateField(),
        ),
    ]
