# Generated by Django 3.2.6 on 2021-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_auto_20210901_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
