# Generated by Django 3.2.6 on 2021-09-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_auto_20210901_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='date'),
        ),
    ]
