# Generated by Django 3.2.6 on 2021-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_alter_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='date',
            field=models.DateField(),
        ),
    ]
