# Generated by Django 3.2.6 on 2021-09-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0006_auto_20210901_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='date',
            new_name='chapter_date',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='date',
            new_name='module_date',
        ),
    ]
