# Generated by Django 3.2.6 on 2021-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0007_auto_20210902_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_date',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_date',
        ),
        migrations.AddField(
            model_name='chapter',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='module',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='date'),
        ),
    ]
