# Generated by Django 3.2.6 on 2021-09-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0008_auto_20210902_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, help_text='Required. 150 characters or fewer. digits only.', max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_title',
            field=models.CharField(blank=True, help_text='Required. 250 characters or fewer. digits only.', max_length=250, null=True, verbose_name='module_title'),
        ),
    ]
