# Generated by Django 3.2.6 on 2021-09-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0009_auto_20210902_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Required. 150 characters or fewer. digits only.', max_length=150, null=True, verbose_name='title')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='status')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_image/', verbose_name='category_image')),
                ('date', models.CharField(blank=True, max_length=50, null=True, verbose_name='date')),
            ],
        ),
        migrations.DeleteModel(
            name='module',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AddField(
            model_name='chapter',
            name='category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='category_id'),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='course',
            name='bestseller',
            field=models.IntegerField(blank=True, null=True, verbose_name='bestseller'),
        ),
        migrations.AddField(
            model_name='course',
            name='category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='category_id'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_file',
            field=models.FileField(blank=True, null=True, upload_to='course_file/', verbose_name='course_file'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='course_level'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(blank=True, help_text='Required. 250 characters or fewer. digits only.', max_length=250, null=True, verbose_name='course_title'),
        ),
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='original_price'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='course',
            name='selling_price',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='selling_price'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='total_days'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='total_hours'),
        ),
    ]
