# Generated by Django 3.2.6 on 2021-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0010_auto_20210903_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAlloted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, null=True, verbose_name='category_id')),
                ('course_id', models.IntegerField(blank=True, null=True, verbose_name='course_id')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='course_id')),
                ('course_status', models.IntegerField(blank=True, null=True, verbose_name='course_status')),
                ('date', models.CharField(blank=True, max_length=50, null=True, verbose_name='date')),
            ],
        ),
    ]
