# Generated by Django 3.2.6 on 2021-09-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0011_coursealloted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursealloted',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='course_management.category'),
        ),
    ]
