# Generated by Django 3.2.6 on 2021-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0014_alter_coursealloted_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_ques_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(blank=True, null=True, verbose_name='question_id')),
                ('answer', models.CharField(blank=True, max_length=50, null=True, verbose_name='answer')),
                ('correct_answer', models.IntegerField(blank=True, null=True, verbose_name='correct_answer')),
                ('date', models.CharField(blank=True, max_length=50, null=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='quiz_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, null=True, verbose_name='chapter_id')),
                ('question', models.CharField(blank=True, max_length=50, null=True, verbose_name='question')),
                ('marks', models.CharField(blank=True, max_length=50, null=True, verbose_name='marks')),
                ('question_status', models.IntegerField(blank=True, null=True, verbose_name='question_status')),
                ('date', models.CharField(blank=True, max_length=50, null=True, verbose_name='date')),
            ],
        ),
    ]
