# Generated by Django 3.2.6 on 2021-09-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0016_rename_category_id_quiz_question_chapter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_ques_answer',
            name='answer_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='answer_status'),
        ),
    ]
