# Generated by Django 3.2.6 on 2021-09-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0017_quiz_ques_answer_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_video',
            field=models.FileField(blank=True, null=True, upload_to='chapter_file/', verbose_name='chapter_video'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='parent_id'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, null=True, upload_to='course_video/', verbose_name='course_video'),
        ),
    ]
