# Generated by Django 3.2.6 on 2021-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0018_auto_20210916_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_video',
            field=models.TextField(blank=True, null=True, verbose_name='chapter_video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.TextField(blank=True, null=True, verbose_name='course_video'),
        ),
    ]
