# Generated by Django 3.2.6 on 2021-09-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0019_auto_20210916_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_video',
        ),
    ]
