# Generated by Django 3.2.6 on 2021-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0021_chapter_chapter_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='chapter_video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='course_video'),
        ),
    ]
